### ISSUE TITLE
[BUG] packed files list includes `node_modules` files

### ISSUE THREAD

**Issue by ljharb** [npm/npm-packlist#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See repro steps.

### Expected Behavior

See repro steps.

### Steps To Reproduce

1. Clone https://github.com/ljharb/list-exports
1. `npm install`
1. `cd packages/tests/fixtures/single-spa-layout/project`
1. run this code:
```
const packageDir = process.cwd();
const packlist = require('npm-packlist');
const Arborist = require('@npmcli/arborist');
const arborist = new Arborist({ path: packageDir });
const arbTree = await arborist.loadActual();
const packedFiles = await packlist(arbTree, { path: packageDir });
```
1. observe how `packedFiles` has three `node_modules` files in it; it should have none.
1. if you `rm -rf node_modules`, then `packedFiles` will no longer contain those three files, but since they're not there anymore, that's expected.

### Environment

- npm: 10.2.5
- Node: 21.4.0
- OS: Mac
- platform: Macbook Pro

**Comment by darcyclarke** [comment]
@ljharb it looks like there's an explicit `bundledDependencies: true` definition at the top of your fixtures `package.json` (a little known feature as of `npm@3` - ref. https://github.com/npm/npm-bundled/commit/101a94db5953e508b57de0e7b887964691d2d326) which then turns your defined `dependencies` (ie. `@types/parse5`)  into an explicit `bundleDependencies` definitions post-install (ref. https://github.com/ljharb/list-exports/blob/main/packages/tests/fixtures/single-spa-layout/project/package.json). Because of this, `npm-packlist` will explicitly include the bundled package's contents as per the docs:

> Everything in the root node_modules is ignored, **unless it's a bundled dependency**. If it IS a bundled dependency, and it's a symbolic link, then **the target of the link is included**, not the symlink itself.

If you don't want to bundle that dep then you need to change the `package.json`

**Comment by ljharb** [comment]
Hmm, ok, I think that makes sense - but then why would it a) be flaky and b) not include `@types/parse5/index.d.ts`?

**Comment by darcyclarke** [comment]
1. Not sure about the flakiness, I was able to repro consistently with the steps you provided
2. I was able to see `@types/parse5/index.d.ts` in the set of files returned from `npm-packlist` & it also was included/referenced in your original message in Slack (ref. https://node-tooling.slack.com/archives/CMB9C398C/p1702081224590129?thread_ts=1702080874.793399&cid=CMB9C398C)

Here's the log I got:

```
[
  'LICENSE',
  'node_modules/@types/parse5/LICENSE',
  'dist/esm/single-spa-layout.min.js',
  'dist/system/single-spa-layout.min.js',
  'dist/umd/single-spa-layout.min.js',
  'node_modules/@types/parse5/package.json',
  'package.json',
  'node_modules/@types/parse5/README.md',
  'README.md',
  'dist/types/constructApplications.d.ts',
  'dist/types/constructLayoutEngine.d.ts',
  'dist/types/constructRoutes.d.ts',
  'dist/types/environment-helpers.d.ts',
  'dist/types/utils/find.d.ts',
  'node_modules/@types/parse5/index.d.ts',
  'dist/types/matchRoute.d.ts',
  'dist/types/single-spa-layout-main.d.ts',
  'dist/types/single-spa-layout.d.ts',
  'dist/types/validation-helpers.d.ts'
]
```

**Comment by ljharb** [comment]
hmm, ok well in that case it seems like this is by design, and I'll close it. Thanks for clarifying.
