### ISSUE TITLE
[BUG] npm-shrinkwrap.json should not be published if referenced in .npmignore 

### ISSUE THREAD

**Issue by Atyn** [npm/npm-packlist#51]
# What / Why
npm-pack (https://docs.npmjs.com/cli-commands/pack.html) should not publish npm-shrinkwrap.json when referenced in .npmignore.

## References
> It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

http://doc.codingdict.com/npm-ref/files/shrinkwrap.html

## Suggested solution

Remove row 166 ('/npm-shrinkwrap.json') from function "mustHaveFilesFromPackage".

## Caused issues
When publishing libraries with Lerna with packages referring to each other, "npm install" crashes.

When npm-shrinkwrap.json is published, every package of the published library have a copy of its dependencies. In my case, the installed library takes 10 GB instead of 100MB and "npm install" crashes on some computers.

**Comment by nlf** [comment]
we always include the `npm-shrinkwrap.json` file as it is one of the only ways for a package author to ensure that all of their dependencies meet their exact criteria (the other option is bundling).

the documentation isn't suggesting that `npm-shrinkwrap.json` never be published, more so that it's a better practice for library authors (as in packages that are meant to be consumed by an application, versus direct applications like the npm cli itself) to not include a shrinkwrap so that consumers can control their own dependency tree.

that said, if you have a shrinkwrap, we will always publish it. the better practice would be to not create one and instead rely on the package-lock.json, which provides you the vast majority of the same protections without causing problems for consumers since it will _not_ be included in the published tarball.

**Comment by capricorn86** [comment]
@nlf this bug is causing a quite major issue in my library [Happy DOM](https://github.com/capricorn86/happy-dom).

NPM does not publish `npm-shrinkwrap.json` when it is referenced in .npmignore, but this library seem to have a bug in it causing Lerna to force push `npm-shrinkwrap.json`.

**Comment by nlf** [comment]
as discussed above, this is not a bug, the `npm-shrinkwrap.json` cannot be ignored if it exists. that file's express purpose is to be published so that a package maintainer can ensure they get the exact dependencies their package works with. you can see this behavior here https://github.com/npm/npm-packlist/blob/main/index.js#L300

the `package-lock.json` on the other hand, never gets published. if you only want to ensure that your locked dependencies are not shipped with your package, rename `npm-shrinkwrap.json` back to `package-lock.json`. you'll get the same benefits from it when you're working yourself, and your end users will never receive it.

**Comment by davidortnercybercom** [comment]
@nlf in NPM v6 or lower `package-lock.json` does not lock sub-dependencies. That is why `npm-shrinkwrap.json` was invented.

NPM does not publish `npm-shrinkwrap.json` if it has been explicitly added to `.npmignore`, but this package does.

Anyway, I have solved it temporarily in my project by using Lerna hoist. The long term solution is to move away from using Lerna and use NPM:s new workspace feature instead.
