### ISSUE TITLE
[BUG] node_modules always ignored even if specified in package.json's files entry

### ISSUE THREAD

**Issue by kidonng** [npm/npm-packlist#56]
# What / Why

`node_modules` is always ignored even if it is specified in `package.json`'s `files` entry, which cases `node_modules` in subdirectories can't be bundled with `npm pack`. This doesn't align with `npm publish` which can publish `node_modules` directory.

This issue only applies to npm 7, not npm 6.

## When

* n/a

## Where

* n/a

### Steps to Reproduce

* Create a package.json:

  ```json
  {
    "name": "some-package",
    "files": [
      "lib/node_modules",
      "other-stuff/nested"
    ]
  }
  ```

* Create the following file structure:

  ```
	.
	├── lib
	│  └── node_modules
	└── other-stuff
	   └── nested
  ```

* Run `npm pack`

### Current Behavior

* `lib/node_modules` isn't presented in output file, while `other-stuff/nested` does.

### Expected Behavior

* `lib/node_modules` should be presented in output file as well.

## Who

* n/a

## References

* n/a

**Comment by nlf** [comment]
bundling dependencies is done on a dependency name basis, including your entire `node_modules` in the result here is not supported. that includes a `node_modules` in a child directory, which is a bit of a strange use case since `node_modules` is intended to live next to your package.json.

can you describe your use case more?

if you have a specific dependency you need to ensure is packed and distributed with your package, you'll need to add it by name to the `bundleDependencies` field of your `package.json` which will ensure that package and its dependencies are included.

**Comment by kidonng** [comment]
Oops, seems like I have missed the notification. Sorry for that!

To be honest this is only related to [a packaging issue with pnpm](https://github.com/pnpm/pnpm/issues/2993), which I assume could be a npm regression. But this is no longer relevant now.
